# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - rm -rf qmongr.Rcheck
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'covr::codecov()'

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
